-- AI tenant routing: customer-owned connections, budgets and optimization loops.
-- Additive migration. Secrets are encrypted by the application and stored only in provider_connections.secret_ref.
alter table public.provider_connections add column if not exists capabilities text[] not null default '{}', add column if not exists execution_mode text not null default 'api_key_customer', add column if not exists monthly_budget numeric(12,6), add column if not exists monthly_spend numeric(12,6) not null default 0, add column if not exists last_validated_at timestamptz, add column if not exists revoked_at timestamptz;
alter table public.provider_connections drop constraint if exists provider_connections_execution_mode_check;
alter table public.provider_connections add constraint provider_connections_execution_mode_check check (execution_mode in ('oauth_subscription','api_key_customer','subscription_assisted','local','platform_api'));
create table if not exists public.ai_client_policies (client_id text primary key references public.client_profiles(client_id) on delete cascade, mode text not null default 'balanced', max_attempts integer not null default 3, monthly_budget numeric(12,6), allow_external_fallback boolean not null default true, require_approval boolean not null default true, allowed_providers text[] not null default '{}', updated_at timestamptz not null default now(), check (mode in ('economy','balanced','quality')), check (max_attempts between 1 and 5));
create table if not exists public.ai_usage_events (id uuid primary key default gen_random_uuid(), client_id text not null references public.client_profiles(client_id) on delete cascade, connection_id uuid references public.provider_connections(id) on delete set null, job_id uuid references public.media_jobs(id) on delete set null, ai_run_id uuid references public.ai_runs(id) on delete set null, provider text not null, model text, event_type text not null default 'inference', input_units integer, output_units integer, estimated_cost numeric(12,6) not null default 0, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.ai_optimization_loops (id uuid primary key default gen_random_uuid(), client_id text not null references public.client_profiles(client_id) on delete cascade, job_id uuid references public.media_jobs(id) on delete cascade, artifact_id uuid references public.artifacts(id) on delete set null, iteration integer not null, issue text, action text not null, status text not null default 'planned', estimated_cost numeric(12,6) not null default 0, metadata jsonb not null default '{}', created_at timestamptz not null default now(), unique (job_id, iteration), check (status in ('planned','running','completed','skipped','blocked')));
create index if not exists provider_connections_client_status_idx on public.provider_connections(client_id, status, provider);
create index if not exists ai_usage_events_client_date_idx on public.ai_usage_events(client_id, created_at desc);
create index if not exists ai_optimization_loops_job_idx on public.ai_optimization_loops(job_id, iteration);
alter table public.ai_client_policies enable row level security; alter table public.ai_usage_events enable row level security; alter table public.ai_optimization_loops enable row level security;
revoke all on public.ai_client_policies from anon, authenticated; revoke all on public.ai_usage_events from anon, authenticated; revoke all on public.ai_optimization_loops from anon, authenticated;
grant all on public.ai_client_policies to service_role; grant all on public.ai_usage_events to service_role; grant all on public.ai_optimization_loops to service_role;
